{% set name = "de-pflanzenschutzmittelzulassung" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/de-pflanzenschutzmittelzulassung-{{ version }}.tar.gz
  sha256: 79fddb559471fda269c7ce5699b6082aa21973f7de6ce6301343240b27004752

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - python-dateutil
    - urllib3 >=1.25.3

test:
  imports:
    - deutschland.pflanzenschutzmittelzulassung
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bundesAPI/pflanzenschutzmittelzulassung-api
  summary: ORDS generated API for api-v1
  license: Apache-2.0
  license_file: 
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
